import { StrictMode } from 'react'
import ReactDOM from 'react-dom/client'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import { DirectionProvider } from './context/direction-provider'
import { FontProvider } from './context/font-provider'
import { ThemeProvider } from './context/theme-provider'
// Type-safe route tree generated by TanStack Router
import { routeTree } from './routeTree.gen'
// Global styling entry point
import './styles/index.css'

// Initialize router with preloading strategies and state management
const router = createRouter({
  routeTree,
  defaultPreload: 'intent',
  defaultPreloadStaleTime: 0,
})

// Type augmentation for TanStack Router global state registration
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

// Application entry point with nested context providers
const rootElement = document.getElementById('root')!
if (!rootElement.innerHTML) {
  const root = ReactDOM.createRoot(rootElement)
  root.render(
    <StrictMode>
      <ThemeProvider>
        <FontProvider>
          <DirectionProvider>
            <RouterProvider router={router} />
          </DirectionProvider>
        </FontProvider>
      </ThemeProvider>
    </StrictMode>
  )
}
